### ISSUE TITLE
The knee data you used for training

### ISSUE THREAD

**Issue by Lutieyuan** [hkaggarwal/modl#3]
Hi!

      I saw you have added the demo of  knee data from the NYU, what a good job! 
      But there are many kinds of  knee data corresponding to different sequences in the link you provided, would you to give a introduction about which sequence you choose for training and what is the config for training. 
       By the way, the knee data of one sequence  contains about 20 persons and each person contains  20 or 30 image slices.  So, is there the necessary to use a per-trained K=1 model for initializing your network when reproducing the result provided in the  knee_demo_code.py?

Best!
TIeyuan

**Comment by hkaggarwal** [comment]
We used subjects 1 to 10 from the coronal_pd folder for training purpose.

Yes, First I did pre-training with K=1. Then I used this pre-trained model to initialize the K=10 model for training. Yes, it is possible to directly train with k=10 but currently, I did not test that.
